class InteractionProtocol:
    FIPA_REQUEST: str = "fipa-request"
    FIPA_QUERY: str = "fipa-query"
    FIPA_REQUEST_WHEN: str = "fipa-request-when"
    FIPA_BROKERING: str = "fipa-brokering"
    FIPA_RECRUITING: str = "fipa-recruiting"
    FIPA_PROPOSE: str = "fipa-propose"
    FIPA_SUBSCRIBE: str = "fipa-subscribe"
    FIPA_ENGLISH_AUCTION: str = "fipa-auction-english"
    FIPA_DUTCH_AUCTION: str = "fipa-auction-dutch"
    FIPA_CONTRACT_NET: str = "fipa-contract-net"
    FIPA_ITERATED_CONTRACT_NET: str = "fipa-iterated-contract-net"
    ITERATED_FIPA_REQUEST: str = "iterated-fipa-request"
